AcmeFormTypeBundle:
    resource: "@AcmeFormTypeBundle/Controller/"
    type:     annotation
    prefix:   /FormTypeBundle

AcmeResponseListenerBundle:
    resource: "@AcmeResponseListenerBundle/Controller/"
    type:     annotation
    prefix:   /ResponseListenerBundle

AcmeTransportBundle:
    resource: "@AcmeTransportBundle/Controller/"
    type:     annotation
    prefix:   /TransportBundle

AcmeAndRoleVoterBundle:
    resource: "@AcmeAndRoleVoterBundle/Controller/"
    type:     annotation
    prefix:   /AndRoleVoterBundle

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
