AcmeAndRoleVoterBundle:
    resource: "@AcmeAndRoleVoterBundle/Controller/"
    type:     annotation
    prefix:   /AndRoleVoterBundle

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
